name: star_movie
description: idf flutter lab

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  data:
    path: packages/data
  presentation:
    path: packages/presentation
  firebase_core: 2.1.0
  firebase_crashlytics: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - keys_prod.json
    - keys_sandbox.json
    - flavor_sandbox_config.json
    - flavor_prod_config.json

  uses-material-design: true

