name: star_movie
description: idf flutter lab

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  data:
    path: packages/data
  presentation:
    path: packages/presentation

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - keys.json
    - flavor_config.json

  uses-material-design: true
