name: presentation
description: presentation module
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 1.1.4

  domain:
    path: ../domain

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  assets:
    - assets/splash_screen/
    - assets/icons/
    - assets/test_images/
  fonts:
    - family: SF Pro Text Semibold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
    - family: SF Pro Text Medium
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
    - family: SF Pro Text Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf