name: presentation
description: presentation module
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk:
      flutter
  intl: ^0.17.0
  flutter_svg: 1.1.4
  shimmer: ^2.0.0
  blur: ^3.1.0
  expandable: ^5.0.1
  firebase_analytics: ^9.1.11

  domain:
    path: ../domain

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  assets:
    - assets/splash_screen/
    - assets/icons/
    - assets/test_images/
  fonts:
    - family: SF Pro Text Semibold
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
    - family: SF Pro Text Medium
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
    - family: SF Pro Text Regular
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf

  generate: true
flutter_intl:
  main_locale: en
  enabled: true