name: domain
description: domain module
version: 1.0.0

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  needle_di:
    git: https://github.com/vladimir-hodaryonok-idf/needle_di.git
  collection: ^1.16.0
  json_annotation: ^4.6.0
  url_launcher: ^6.1.6
  package_info_plus: ^3.0.1

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.3.1

environment:
  sdk: '>=2.17.6 <3.0.0'