name: domain
description: domain module
version: 1.0.0

publish_to: 'none'

dependencies:
  get_it: ^7.2.0
  collection: ^1.16.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.3.1

environment:
  sdk: '>=2.17.6 <3.0.0'