name: master_commit

on:
  push:
    branches:
      - master
jobs:
  commit_master:
    name: commit to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: ApiKeysFlutter
        run: |
          touch "keys_prod.json";
          echo "${{ secrets.KEYS_PROD }}" >> keys_prod.json;
          touch "keys_sandbox.json";
          echo "${{ secrets.KEYS_SANDBOX }}" >> keys_sandbox.json;
          cat keys_prod.json;
          cat keys_sandbox.json;
      - name: ApiKeysAndroid
        run: |
          cd android;
          touch "keys.properties";
          echo "${{ secrets.KEYS_FACEBOOK }}" >> keys.properties;
          cat keys.properties;
      - name: GetDependenciesAndGenerateDomain
        run: |
          cd packages/domain/
          flutter pub get && flutter packages pub run build_runner build
      - name: GetDependenciesAndGenerateData
        run: |
          cd packages/data/
          flutter pub get && flutter packages pub run build_runner build
      - name: GetDependenciesPresentation
        run: |
          cd packages/presentation/
          flutter pub global activate intl_utils 2.7.0
          flutter pub get
      - name: GeneratePresentation
        run: |
          cd packages/presentation/
          flutter pub global run intl_utils:generate
      - name: AppPubGet
        run: flutter pub get
      - name: Build Prod Release Apk
        run: flutter build apk --release -t lib/production.dart --flavor Prod
      - name: Push APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-prod-release.apk
          tag: Release
          token: ${{ secrets.TOKEN_G_H }}
