name: main_pull_request

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - master
jobs:
  pull_request_opened:
    name: Pull request to master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ">=2.17.6 <3.0.0"
    - run: flutter pub get
    - run: flutter test
    - run: flutter build appbundle
