name: main_pull_request

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - master
jobs:
  pull_request_opened:
    name: Pull request to master
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - name: Flutter upgrade
        run: flutter upgrade
      - name: ApiKeysFlutter
        run: |
          touch "keys_sandbox.json";
          touch "keys_prod.json";
          echo "${{ secrets.KEYS_SANDBOX }}" >> keys_sandbox.json;
      - name: ApiKeysAndroid
        run: |
          touch "keys.properties";
          echo "${{ secrets.KEYS_FACEBOOK }}" >> keys.properties;
        working-directory: android/
      - name: GetDependenciesAndGenerateDomain
        run: |
          flutter pub get && flutter packages pub run build_runner build
        working-directory: packages/domain/
      - name: GetDependenciesAndGenerateData
        run: |
          flutter pub get && flutter packages pub run build_runner build
        working-directory: packages/data/
      - name: GetDependenciesPresentation
        run: |
          flutter pub global activate intl_utils 2.7.0
          flutter pub get
        working-directory: packages/presentation/
      - name: GeneratePresentation
        run: |
          flutter pub global run intl_utils:generate
        working-directory: packages/presentation/
      - name: AppPubGet
        run: flutter pub get && flutter packages pub run build_runner build
      - name: Integration Test
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 29
          target: playstore
          emulator-options: -dns-server 8.8.8.8 -timezone Europe/Amsterdam
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test --flavor SandBox
      - name: Tests
        run: flutter test
      - name: Build Sandbox Debug Apk
        run: flutter build apk --debug -t lib/sand_box.dart --flavor SandBox
      - name: Push APK to Releases
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.5
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: idk_lab
          file: build/app/outputs/flutter-apk/app-sandbox-debug.apk
